"""
Agent 5: Interactive Policy Analysis Agent
Phase 1 — Policy interview (8 questions)
Phase 2 — Guiding principles generated by Claude
Phase 3 — Live vendor cost intelligence
Phase 4 — Policy verdict for every OS/DB row
Project window: 1 Apr 2026 → 30 Jun 2028
"""
import anthropic
import json
import pandas as pd
import streamlit as st
from datetime import date, datetime

PROJECT_END = date(2028, 6, 30)
TODAY       = date.today()

POLICY_QUESTIONS = [
    {"id": "q1", "key": "eol_tolerance",
     "q": "Risk tolerance for EOL software during the project (Apr 2026 – Jun 2028)?",
     "opts": ["Zero — all EOL must be remediated before project end",
              "Low — EOL only with compensating controls (WAF, IPS, isolation)",
              "Medium — EOL acceptable if vendor ESU purchased",
              "High — EOL acceptable if no known critical CVEs"]},
    {"id": "q2", "key": "min_runway",
     "q": "Minimum support runway required at project end (Jun 2028)?",
     "opts": ["24+ months past Jun 2028 (supported until Jun 2030+)",
              "12+ months past Jun 2028 (supported until Jun 2029+)",
              "Active support on 30 Jun 2028 is sufficient",
              "No minimum — assessed case by case"]},
    {"id": "q3", "key": "esu_budget",
     "q": "Is ESU / paid vendor extension budget approved?",
     "opts": ["Yes — ESU budget is approved",
              "Limited — Tier-1 critical systems only",
              "No — must upgrade or replace",
              "Under review"]},
    {"id": "q4", "key": "remediation",
     "q": "Preferred remediation when a product reaches EOL?",
     "opts": ["In-place upgrade to latest supported version (same vendor)",
              "Migrate to open-source (e.g. Oracle DB → PostgreSQL)",
              "Migrate to cloud-managed service (e.g. SQL Server → Azure SQL)",
              "Hybrid — upgrade first, cloud migrate in phase 2"]},
    {"id": "q5", "key": "compliance",
     "q": "Compliance / regulatory requirements in scope?",
     "opts": ["PCI DSS — payment card data",
              "HIPAA — health data",
              "SOX — financial systems",
              "Multiple / internal policy only"]},
    {"id": "q6", "key": "oracle_stance",
     "q": "Stance on Oracle licensing costs?",
     "opts": ["Actively reducing Oracle spend — OSS migration preferred",
              "Oracle acceptable if it is best-fit",
              "Oracle is strategic — expanding estate acceptable",
              "Evaluate Oracle vs alternatives case by case"]},
    {"id": "q7", "key": "windows_path",
     "q": "Preferred path when Windows OS reaches EOL?",
     "opts": ["Upgrade to Windows 11 / Server 2025",
              "Purchase ESU and plan upgrade post-project",
              "Migrate to Linux (RHEL / Ubuntu) where possible",
              "Evaluate Windows 365 / Azure Virtual Desktop"]},
    {"id": "q8", "key": "cost_weight",
     "q": "How should cost influence the final recommendation?",
     "opts": ["Cost is primary — cheapest compliant option wins",
              "Cost important but security/compliance takes precedence",
              "TCO over 3 years is the deciding metric",
              "Cost is a factor but strategic alignment matters more"]},
]

VERDICTS = ["CRITICAL", "UPGRADE NOW", "EXTEND + PLAN", "REPLACE", "CLOUD MIGRATE", "MONITOR"]


class PolicyAnalysisAgent:

    def __init__(self, api_key: str):
        self.client = anthropic.Anthropic(api_key=api_key)
        self.model  = "claude-sonnet-4-6"

    @staticmethod
    def init_session():
        defaults = {
            "a5_status":     "idle",
            "a5_answers":    {},
            "a5_principles": [],
            "a5_costs":      {},
            "a5_os_done":    False,
            "a5_db_done":    False,
        }
        for k, v in defaults.items():
            if k not in st.session_state:
                st.session_state[k] = v

    @staticmethod
    def reset():
        for k in ["a5_status", "a5_answers", "a5_principles",
                  "a5_costs", "a5_os_done", "a5_db_done"]:
            st.session_state.pop(k, None)
        PolicyAnalysisAgent.init_session()

    # ── Phase 2: Generate guiding principles ──────────────────────────────────
    def generate_principles(self, answers: dict) -> list:
        answers_text = "\n".join(
            f"Q: {q['q']}\nA: {answers.get(q['key'], 'Not answered')}"
            for q in POLICY_QUESTIONS
        )
        prompt = (
            f"Based on these org policy answers, generate 6-8 named Guiding Principles "
            f"(GP-01, GP-02…) for migration decisions. "
            f"Project window: 1 Apr 2026 → 30 Jun 2028. Today: {TODAY}.\n\n"
            f"POLICY ANSWERS:\n{answers_text}\n\n"
            f"Return ONLY a JSON array, no markdown:\n"
            f'[{{"code":"GP-01","title":"Short 4-word title",'
            f'"rule":"One clear sentence rule.","trigger":"If X → Y"}}]'
        )
        try:
            resp = self.client.messages.create(
                model=self.model, max_tokens=2000,
                messages=[{"role": "user", "content": prompt}]
            )
            text = resp.content[0].text.strip()
            if "```" in text:
                text = text.split("```json")[-1].split("```")[0] if "```json" in text \
                       else text.split("```")[1].split("```")[0]
            s, e = text.find("["), text.rfind("]")
            if s != -1 and e > s:
                return json.loads(text[s:e+1])
        except Exception:
            pass
        return [{"code": "GP-01", "title": "Zero EOL Tolerance",
                 "rule": "No EOL software permitted past 30 Jun 2028.",
                 "trigger": "EOL before Jun 2028 → Upgrade immediately"}]

    # ── Phase 3: Live vendor cost intelligence ────────────────────────────────
    def fetch_costs(self, progress_cb=None) -> dict:
        searches = [
            ("Windows ESU",      "Windows Server 2012 2016 Extended Security Update pricing cost per server 2026"),
            ("SQL Server ESU",   "SQL Server 2012 2014 2016 Extended Security Updates cost per core 2026"),
            ("Oracle Support",   "Oracle Database annual support cost 22% of license extended support surcharge 2026"),
            ("RHEL Subscription","Red Hat Enterprise Linux subscription cost per server socket 2026"),
            ("IBM Db2/AIX",      "IBM Db2 AIX annual support maintenance cost per processor 2026"),
            ("Cloud Options",    "Azure SQL Managed Instance AWS RDS PostgreSQL annual cost per instance 2026"),
        ]
        costs = {}
        n = len(searches)
        for i, (vendor, query) in enumerate(searches):
            if progress_cb:
                progress_cb(i / n, f"Searching cost: {vendor}...")
            try:
                resp = self.client.messages.create(
                    model=self.model, max_tokens=350,
                    tools=[{"type": "web_search_20250305", "name": "web_search"}],
                    messages=[{"role": "user", "content":
                        f"Search: {query}\nReturn a 2-sentence cost summary with specific figures."}]
                )
                costs[vendor] = "".join(
                    b.text for b in resp.content if hasattr(b, "text")
                ).strip() or "Cost data not found via web search."
            except Exception:
                costs[vendor] = f"Web search unavailable. Typical: {self._default_cost(vendor)}"
        if progress_cb:
            progress_cb(1.0, "✅ Cost data fetched.")
        return costs

    def _default_cost(self, vendor: str) -> str:
        defaults = {
            "Windows ESU":       "Windows Server 2012 R2 ESU ~$198/server/year (Year 3). Azure Arc provides free ESU.",
            "SQL Server ESU":    "SQL Server 2016 ESU ~$1,418/core/year (Year 1). Free on Azure.",
            "Oracle Support":    "Oracle annual support ~22% of license list price. Extended Support adds 10% surcharge.",
            "RHEL Subscription": "RHEL Standard ~$800/year/socket-pair. Premium ~$1,300/year.",
            "IBM Db2/AIX":       "IBM Db2 support ~20% of license annually via Passport Advantage.",
            "Cloud Options":     "Azure SQL MI ~$465/month (4 vCores). AWS RDS PostgreSQL ~$200/month.",
        }
        return defaults.get(vendor, "Contact vendor for current pricing.")

    # ── Phase 4: Analyse rows ─────────────────────────────────────────────────
    def analyse_os(self, df, principles, costs, progress_cb=None):
        return self._analyse(df, "OS", principles, costs, progress_cb)

    def analyse_db(self, df, principles, costs, progress_cb=None):
        return self._analyse(df, "DB", principles, costs, progress_cb)

    def _analyse(self, df, kind, principles, costs, progress_cb):
        df = df.copy()
        if "Policy Recommendation" not in df.columns:
            df["Policy Recommendation"] = ""
        if "Verdict" not in df.columns:
            df["Verdict"] = ""

        gp_text   = "\n".join(f"{p['code']}: {p['title']} — {p['rule']}" for p in principles)
        cost_text = "\n".join(f"{v}: {s}" for v, s in costs.items())
        rows      = df.to_dict("records")
        total     = len(rows)
        batch     = 15

        for i in range(0, total, batch):
            chunk = rows[i:i+batch]
            if progress_cb:
                progress_cb(i / total,
                    f"🧠 Analysing {kind} rows {i+1}–{min(i+batch,total)} of {total}...")

            if kind == "OS":
                rows_text = "\n".join(
                    f"KEY={r['OS Version']} | "
                    f"Mainstream={r.get('Mainstream/Full Support End','')} | "
                    f"Extended={r.get('Extended/LTSC Support End','')} | "
                    f"Upgrade={r.get('Upgrade','')} | Replace={r.get('Replace','')} | "
                    f"A2={r.get('Recommendation','')[:60]}"
                    for r in chunk
                )
            else:
                rows_text = "\n".join(
                    f"KEY={r['Database']} {r['Version']} | "
                    f"Status={r.get('Status','')} | "
                    f"Mainstream={r.get('Mainstream / Premier End','')} | "
                    f"Extended={r.get('Extended Support End','')} | "
                    f"Replace={r.get('Replace','')} | Alt={r.get('Primary Alternative','')} | "
                    f"A2={r.get('Recommendation','')[:60]}"
                    for r in chunk
                )

            prompt = (
                f"GUIDING PRINCIPLES:\n{gp_text}\n\n"
                f"VENDOR COSTS:\n{cost_text}\n\n"
                f"PROJECT: 1 Apr 2026 → 30 Jun 2028  |  Today: {TODAY}\n\n"
                f"RECORDS TO ANALYSE:\n{rows_text}\n\n"
                f"For each KEY return a Policy Recommendation starting with exactly one of:\n"
                f"CRITICAL / UPGRADE NOW / EXTEND + PLAN / REPLACE / CLOUD MIGRATE / MONITOR\n"
                f"Format: VERDICT — Reason. Cost note if relevant. GP reference.\n\n"
                f"Return ONLY a JSON object: {{\"KEY_value\": \"VERDICT — ...\", ...}}"
            )

            try:
                resp = self.client.messages.create(
                    model=self.model, max_tokens=3000,
                    messages=[{"role": "user", "content": prompt}]
                )
                text = resp.content[0].text.strip()
                if "```" in text:
                    text = text.split("```json")[-1].split("```")[0] if "```json" in text \
                           else text.split("```")[1].split("```")[0]
                s, e = text.find("{"), text.rfind("}")
                recs = json.loads(text[s:e+1]) if s != -1 and e > s else {}
            except Exception:
                recs = {}

            for j, row in enumerate(chunk):
                key = row["OS Version"] if kind == "OS" \
                      else f"{row['Database']} {row['Version']}"
                rec = recs.get(key, self._rule_based(row, kind))
                verdict = next((v for v in VERDICTS if rec.upper().startswith(v)), "MONITOR")
                df.at[i + j, "Policy Recommendation"] = rec
                df.at[i + j, "Verdict"] = verdict

        if progress_cb:
            progress_cb(1.0, f"✅ {kind} policy analysis complete.")
        return df

    def _rule_based(self, row, kind):
        def _parse(s):
            try:
                return datetime.strptime(str(s)[:10], "%Y-%m-%d").date()
            except Exception:
                return None

        if kind == "OS":
            end  = _parse(row.get("Extended/LTSC Support End", "")) \
                or _parse(row.get("Mainstream/Full Support End", ""))
            name = row.get("OS Version", "?")
        else:
            end  = _parse(row.get("Extended Support End", "")) \
                or _parse(row.get("Mainstream / Premier End", ""))
            name = f"{row.get('Database','?')} {row.get('Version','?')}"

        if not end:
            return f"MONITOR — Support dates unclear for {name}. Verify manually. (GP-02)"
        if end < TODAY:
            return f"CRITICAL — {name} is already EOL as of {end}. Immediate action required. (GP-01)"
        if end < PROJECT_END:
            return f"UPGRADE NOW — {name} support ends {end}, before project end Jun 2028. Upgrade now. (GP-01)"
        if end < date(2030, 6, 30):
            return f"EXTEND + PLAN — {name} supported until {end}. Plan upgrade within project. (GP-02)"
        return f"MONITOR — {name} supported until {end}, well past project end. No action needed now. (GP-05)"
